### ISSUE TITLE
Electric Car Sound

### ISSUE THREAD

**Issue by sauer-m** [TheDIYGuy999/Rc_Engine_Sound#1]
Hi!
I badly need exactly this library!
Thanks for that :)

Unfortunately I need the sound of an electric car (no hybrid, just electric engines).
Im not able to generate a sound for this.
I tried a lot, even simple sin waves but no effort.

Maybe Im doing something wrong during the conversion:

Audacity -> WAV unsigned 8bit - 16kHz ->Wav2C -> Arduino IDE

Dont know how to go on... :/

**Comment by TheDIYGuy999** [comment]
Have a look at this video: https://www.youtube.com/watch?v=-UPb9nRPHV8&t=27s

Everything is explained there step by step
