### ISSUE TITLE
Please Add Start Sound 

### ISSUE THREAD

**Issue by ArianGhafouri** [TheDIYGuy999/Rc_Engine_Sound#3]
Hi @TheDIYGuy999 

I needed this library and you solved my problem thanks in advance !
but there is problem, it hasn't got engine start sound. I looked for PCM Sound examples and some libraries but i couldn't add it. i have some problems with converting wav to c but please please please add a start sound to that program, it would be very complete...

I look forward to hear from you.

**Comment by tsoyi** [comment]
Hi @TheDIYGuy999,

I also look forward seeing Start Sound added in this library! Or can you guide me how to modify and add this function? Thank you!

**Comment by TheDIYGuy999** [comment]
Two different start sounds are now included, as well as new Scania and Ural-4320 V8 Diesel sounds.
